### ISSUE TITLE
[Intermittent] Bus timer starts before the question is loaded

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#100]
Steps:
1. Start the /bus quiz
2. Click on the start button
3. Wait for timer to expire
4. In the modal, click on Return Home
5. Start the /bus quiz again
6. Click on the start button

Result: Timer started but question wasn't loaded. It was observed only once, so low severity.
<img width="1680" alt="Screen Shot 2021-09-12 at 2 10 56 pm" src="https://user-images.githubusercontent.com/62487509/132972238-737d5038-59e1-44ba-9358-5c4cc2b37c0d.png">

**Comment by ale-sanchez-g** [comment]
delay on the API to respond

**Comment by ale-sanchez-g** [comment]
functionality removed on versin 65
