### ISSUE TITLE
It is possible to lower someone else's score

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#102]
Steps:
1. Log in as a user who already has a high score
2. Play a bus quiz
3. Answer the question correctly
4. Go to leaderboard

Result: This user's score gets overwritten
Expectation: Someone's score should be updated only if the new score is more than the previous score
Assumption: Leaderboard is the list of user's high scores and not current/most recent score

**Comment by ale-sanchez-g** [comment]
This is as per design. Until we introduce login and password for users.
