### ISSUE TITLE
Incorrect value of score for "Go to a Public place" battle

### ISSUE THREAD

**Issue by arpitdon** [ale-sanchez-g/responsivefight#115]
User is getting incorrect score for passing the "Go to a Public place" battle.

Steps to reproduce - 
1. Login to the battlefield with a valid user
2. Play the "Go to a Public place" battle.
3. Select correct option and observe the success message.
4. Check the final score.

Expected score - 100
Actual Score - 90

Environment - https://responsivefight.herokuapp.com/covid

Severity - Major

Priority - High

Screenshot - (Not able to get screenshot again)

**Comment by ale-sanchez-g** [comment]
unable to replicate
