### ISSUE TITLE
It is asking to create user(Warrior) even it is created before

### ISSUE THREAD

**Issue by geethakarthikeyan** [ale-sanchez-g/responsivefight#116]
Steps to reproduce

1. In https://responsivefight.herokuapp.com/, create user and start the journey for the user
2. Do some operation after clicking Are you game link?
3. Give some incorrect answer. Click back to home
Expected Result: It can show options to resume operations for existing user
Actual Result:  It is asking to create user again even for the existing user

Environment - https://responsivefight.herokuapp.com/covid

Severity - Minor

Priority - Low

**Comment by ale-sanchez-g** [comment]
this is as per design.
