### ISSUE TITLE
Security Issue: Persons accessing the system can use existing user and scores

### ISSUE THREAD

**Issue by geethakarthikeyan** [ale-sanchez-g/responsivefight#118]
**Application should have authorization option for the user to sign in or sign out**

Steps to reproduce
1. Create a warrior and start your journey by creating user and click start journey button for user
2. Perform some battles. click back to move to Homepage
3. After some time if any user accessing the system can reuse the existing user stored in dropdown

Expected: 
1.System should not cache user details while creating warriors or
2. It should have option to sign out/sign in for the user  with credentials

Actual: It is caching user name while creating warriors. There is no option to sign in/sign out for the user
Severity: Major
Priority: High

Attached screenshot for the same
![securityissue](https://user-images.githubusercontent.com/41196807/140713028-e3de0a1b-9bb6-4ff3-83d7-f1c98b61e03e.PNG)

**Comment by ale-sanchez-g** [comment]
building this feature at the moment

**Comment by ale-sanchez-g** [comment]
this has been resolved with the registration and login functionality
