### ISSUE TITLE
It is not showing error message popup in one of the question in Are you game link

### ISSUE THREAD

**Issue by geethakarthikeyan** [ale-sanchez-g/responsivefight#119]
Steps to reproduce
1. Create warrior and start the journey by clicking start the journey button
2. Select Are you game? link from the battle fields displayed
3. start answering the question
4. For one of the question (In screenshot), if I select wrong answer, it is not showing the popup which mention it as wring answer

Expected: It should show properly the popup for right answer/wrong answer
Actual: Not showing popup for wrong answer for the question- Someone sits next to you, and is beginning to cough, what do you do?

Severity : Minor
Priority: Medium
Attached screen shot for the same
![heroukissuenotshowingwronganswerpopup](https://user-images.githubusercontent.com/41196807/140714659-f9059a0c-2e1c-446c-80da-8ddc51b4f6c4.PNG)

**Comment by ale-sanchez-g** [comment]
fixed
