### ISSUE TITLE
The site always craches after clicking the the choice for several times.

### ISSUE THREAD

**Issue by wds33817** [ale-sanchez-g/responsivefight#125]
After creating a user(%5c), and go to battle, and there are no characters in the first question, but you could click around, after clicking for several times of options, the animation stops, and the site crashed. 

It turns out:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by ale-sanchez-g** [comment]
DB for user journey was full.

Clean up DB and system is back up

**Comment by wds33817** [comment]
Application error again, seems like there is logic error.

**Comment by ale-sanchez-g** [comment]
@wds33817 can you please provide steps to recreate this issue.

- Step by step
- Screenshots

We are currently unable to replicate in the lower environment with user %5c or (%5c)

Also, if you can attach the network traffic so we can see what is the traffic and error responses

**Comment by ale-sanchez-g** [comment]
replicated and the issue is when DB is clean up.
