### ISSUE TITLE
Anonymous users can enter the battlefield screen 

### ISSUE THREAD

**Issue by Prasannakanderi** [ale-sanchez-g/responsivefight#126]
Description:
Users without warrior name can enter the game.  i.e. Create button is enabled without signing in. 

Reproduction steps:
1. Go to https://responsivefight.herokuapp.com/
2. Leave 'Tell me your warrior name' section blank
3. Click 'Create Warrior' button
4. Click "start the journey" button
5. User enters the battle field screen

Actual Result:
Anonymous user can enter the battle field screen to play the game

Expected Result:
In Step2, restrict the user from clicking the 'Create button'. Create button must be disabled if no user details are entered in 'Tell me your warrior name' section.

**Comment by ale-sanchez-g** [comment]
as per design this are guest

Rego and login feature WIP 🔢
