### ISSUE TITLE
CAT - If Username has no text/letter, the news section does not display any text.

### ISSUE THREAD

**Issue by sweetysh2021** [ale-sanchez-g/responsivefight#127]
Create username/warrior name with alphabet and numeric letters - works fine.
Create username/warrior name with atleast one alphanumeric and rest special characters - works fine.
Create username/warrior name without entering anything - works fine - uses guest login.
Create username/warrior name with special characters only or special characters with numbers only- Issue - the text in the story header of the news section is not displayed neither the text for the 2 buttons.

**Comment by ale-sanchez-g** [comment]
This has been resolved
