### ISSUE TITLE
Warrior name missing on the leaderboard when the user logs in again

### ISSUE THREAD

**Issue by Prasannakanderi** [ale-sanchez-g/responsivefight#129]
Reproduction steps:
1. Go to https://responsivefight.herokuapp.com/
2. Click on "Create Warrior" button
3. Enter the warrior name as "Sample"  
4. Click  "start the journey" button
5. Select "Choose the battle field"
6. Select "Visit all battlefields" and press "Are you game?" button
7. Answer all the questions with correct answer
8. Finish the game and go to leaderboard.
9. Observe that warrior "Sample" is available in the leaderboard
10. Repeat steps 1 to 8
11. Observe that warrior "Sample" is not appearing in the leaderboard.

Actual Result:
In step 11, "Sample" warrior missing on the leaderboard with respective score

Expected Result:
In step 11, "Sample" warrior should appear on the leaderboard with respective score

**Comment by ale-sanchez-g** [comment]
Unable to replicate
