### ISSUE TITLE
No proper username authentication while logging in responsivefight application

### ISSUE THREAD

**Issue by seemarya** [ale-sanchez-g/responsivefight#134]
Issue 1: No authentication if a user enters space or already existing name to create a warrior name to login to the application.
Expected: There should be restrictions i.e. valid username authentication for what is allowed and what is not allowed.

**Comment by ale-sanchez-g** [comment]
@seemarya please split into multiple issues so we can address them each

**Comment by ale-sanchez-g** [comment]
registration and login feature under construction

**Comment by ale-sanchez-g** [comment]
Registration and login implemented
