### ISSUE TITLE
Issue Id 1 : User Can Login As a Guest

### ISSUE THREAD

**Issue by raj21062017** [ale-sanchez-g/responsivefight#141]
Test Step 1.Open the Url https://responsivefight.herokuapp.com/ and Enter
Test Step 
![1](https://user-images.githubusercontent.com/59826098/146677293-1c067214-3dc6-403f-8143-93a0c1df1453.PNG)
2.Create a Warrior name and Enter.

Issue Description: 
The Warrior name field is also accepting the user as Guest even though the user didn’t create the Warrior name.

**Comment by ale-sanchez-g** [comment]
as per design

Registration and login feature coming soon
