### ISSUE TITLE
Issue Id 2: Spelling Mistake

### ISSUE THREAD

**Issue by raj21062017** [ale-sanchez-g/responsivefight#142]
Test Step 1.Open the Url https://responsivefight.herokuapp.com/ and Enter
Test Step 2.Create a Warrior name and Enter
Test Step 3.Once the Warrior name is created and clicked on the button “Start your journey ”, it Opens and Url https://responsivefight.herokuapp.com/covid  with the options to choose for the quiz.
Test Step 4. Choose the options and click on them to start answering the quiz.
Test Step 5.Selected “Are you game” option.
Test Step 5.1) Opened a window and it shows the Warning message with a start button.

Issue Description : 
Found spelling mistake “acumulated” instead of “accumulated”.
![2](https://user-images.githubusercontent.com/59826098/146677883-de1636da-21de-4135-b247-6bd7916b415f.PNG)

**Comment by ale-sanchez-g** [comment]
fixed
