### ISSUE TITLE
Issue Id 12 : There is a Timer without Prior Notice

### ISSUE THREAD

**Issue by raj21062017** [ale-sanchez-g/responsivefight#152]
Test Step 1.Open the Url https://responsivefight.herokuapp.com/ and Enter
Test Step 2.Create a Warrior name and Enter
Test Step 3.Once the Warrior name is created and clicked on the button “Start your journey ”, it Opens and Url https://responsivefight.herokuapp.com/covid with the options to choose for the quiz.
Test Step 4. Choose the options and click on them to start answering the quiz.
Test Step 5.Selected “Are you game” option.
Test Step 6.Clicked on “Take the bus ” Option.
Test Step 6.1) Once clicked on the “Take the bus” button , it showed a window with “Start” button.
Test Step 6.1.1)Once clicked on the “Start ” button , it opened an url https://responsivefight.herokuapp.com/bus with two clickable buttons.

Issue Description : 
There is timer for the quiz which is not mentioned before entering into the page.
![12](https://user-images.githubusercontent.com/59826098/146680446-f5c2b2bc-39db-4e48-a24e-087572f4524a.PNG)

**Comment by ale-sanchez-g** [comment]
Timer warning feature request

**Comment by ale-sanchez-g** [comment]
remove version 65
