### ISSUE TITLE
Issue Id 14 :Sub-headings are Mis-matched.

### ISSUE THREAD

**Issue by raj21062017** [ale-sanchez-g/responsivefight#154]
Test Step 1.Open the Url https://responsivefight.herokuapp.com/ and Enter
Test Step 2.Create a Warrior name and Enter
Test Step 3.Once the Warrior name is created and clicked on the button “Start your journey ”, it Opens and Url https://responsivefight.herokuapp.com/covid with the options to choose for the quiz.
Test Step 4. Choose the options and click on them to start answering the quiz.
Test Step 5.Selected “Are you game” option.
Test Step 6.Clicked on “Take the bus ” Option.
Test Step 6.1) Once clicked on the “Take the bus” button , it showed a window with “Start” button.
Test Step 6.1.1)Once clicked on the “Start ” button , it opened an url https://responsivefight.herokuapp.com/bus with two clickable buttons.
Test Step 6.1.2)Once clicked on the correct option , it opened a window with two clickable buttons “Try the next battle” and “Check your final score”.
Test Step 6.1.3)Once clicked on the “Try the next door ” button , it opened an URL https://responsivefight.herokuapp.com/office and a window with “Start” button.

Issue Description:
Sub-headings on the window are not matched.
![14](https://user-images.githubusercontent.com/59826098/146680825-5567745d-8e5c-4be5-9a14-321f8b09e65e.PNG)

**Comment by ale-sanchez-g** [comment]
This is as per design for the Bug hunt will not fix for other candidates to find
