### ISSUE TITLE
No Restriction for the user name while creating a warrior

### ISSUE THREAD

**Issue by ManjuDineshKumar** [ale-sanchez-g/responsivefight#157]
Description : While creating a warrior, user name input doesn't have any restriction and it allows even only special characters , numbers only or any kind of combination

Steps to reproduce:
1.  open Covid-19 game Application 
2.  Enter any input like below  for the field "Tell me your warrior name"
a. @#$ 
b. aa
c.12adf

Expected result : there should be some restriction and allowed number of characters
Actual result : User can use any combination

**Comment by ale-sanchez-g** [comment]
This is as per design. given that a user name could be `@alpha$Team`
