### ISSUE TITLE
Login - Text Box fields values for Username and Password are not getting Cleared Post "Cancel" Option

### ISSUE THREAD

**Issue by sharikrishna0008** [ale-sanchez-g/responsivefight#199]
Issue Description:
In login page, Values entered in the User Name and Password Fields are not getting cleared when user clicks on Cancel Option.

Steps to Reproduce:

1.Browse the URL : https://responsivefight.herokuapp.com/
2.Click on "Login" button.
3.Enter Username and Password.
4.Click on "Cancel" Button instead of "Login Warrior" Button.
5. User should be able to see the Username and Password values instead of Empty Text box.
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/92024133/167296565-ad903e4a-8a28-47ee-859a-ab662176417f.png">

**Comment by ale-sanchez-g** [comment]
fixed
