### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by ale-sanchez-g** [ale-sanchez-g/responsivefight#41]
After images where clean up, there is a section that the image URL is broken

![image](https://user-images.githubusercontent.com/8701973/87791128-1ebb0500-c885-11ea-8207-f0e6ba297c44.png)

**Comment by asanchezgiraldo** [comment]
Also, the COVID page is not desktop friendly

![image](https://user-images.githubusercontent.com/15203863/87792850-cafdeb00-c887-11ea-88c9-28872e3e490a.png)
