### ISSUE TITLE
Battle field - 'i' icon on the top right of the page does display the correct information

### ISSUE THREAD

**Issue by prachimunjal** [ale-sanchez-g/responsivefight#60]
**Description** 

On click of the icon 'i' on the top right of the battlefield page, user gets a message stating " Some static or API fetched information".

**Steps to Reproduce -**

1. Navigate to the application - responsivefight.herokuapp.com
2. Enter warrior name and click on "Create Warrior" button.
3. Click on "Start your journey <WarriorName>"
4. Click on any challenge for instance - "Take the Bus".
5. Click on "Start" button on the pop up .
6. Click on "i" icon on the top right of the page.

**Expected** - On click on "i" icon information about the page should be displayed.
**Actual** - Some static of API fetched information" is displayed.

**Environment details -**
URL - http://responsivefight.herokuapp.com/

Note - This issue is applicable on all the pages which have "i" icon, all the question pages for challenges.

**Screenshot-**

![image](https://user-images.githubusercontent.com/84520912/124376909-bf474680-dcdb-11eb-813e-1ee05c0f0782.png)

**Comment by ale-sanchez-g** [comment]
removed this functionality
