### ISSUE TITLE
[FrontEnd] Timer pop up UI issue.

### ISSUE THREAD

**Issue by MonikaKohli** [ale-sanchez-g/responsivefight#64]
Steps:
1. Start any challenge from the Home Page.
2. Now select the wrong answer and pop up appears for the wrong answer.
3. Now notice that the timer keeps running in the background.

Observation:
1. The timer should stop there and then when the user gives wrong answer.
2. If we keep on running the timer, then the timeout pop up appears and TRY AGAIN button is trimmed from bottom.

**Comment by ale-sanchez-g** [comment]
functionality to be removed on version 65
