### ISSUE TITLE
[FrontEnd] Timer Stops if user taps on Cross icon on any challenge success of wrong answer pop up.

### ISSUE THREAD

**Issue by MonikaKohli** [ale-sanchez-g/responsivefight#65]
1. Start any challenge from home screen.
2. Now give correct answer or wrong answer.
3. Pop up appears of success or fail.
4. Now tap on Cross icon of the pop up.
5. The pop up closes.

Observation: 
The timer stops in background.

Expected:
The timer should start again in case user crosses the pop up.

**Comment by ale-sanchez-g** [comment]
removed 'x' from the pop up to prevent issue on the timer
