### ISSUE TITLE
Click "Try again" in the battle field "Are you game?" after selecting wrong answer, the page will be turned to login page

### ISSUE THREAD

**Issue by nicoleliua** [ale-sanchez-g/responsivefight#69]
Test steps:

1. Create warrior name and start the journey from the login page.
2. Start the challenge "Are you game?" from the home Page.
3. Now select the wrong answer and click "Try again"
4. The page will be turned to the login page.

Observation:
1. The page should stay in the existing challenge page instead of the login page, and the user can continue playing the challenge.

**Comment by ale-sanchez-g** [comment]
changed text, user is expected to start again
