### ISSUE TITLE
[UI] Userstage gets created even on providing duplicate player name - though api error is seen in network logs.

### ISSUE THREAD

**Issue by asbhat1069** [ale-sanchez-g/responsivefight#79]
Steps:
1. Create a player TEST1 and take any challenge
2. Navigate back to player creation page and enter the same name TEST1 . User Stage gets created.
    Checking network logs one can see the API error of 400 bad request

Expected:
Error raised with message duplicate user.

**Comment by ale-sanchez-g** [comment]
This is as per design as we are not authenticating users, so we are just updating the user.
