### ISSUE TITLE
[UI] Timer begins even before clicking 'start' in the battlefield challenge and times out with try again popup if challenge not started before times runs out.

### ISSUE THREAD

**Issue by asbhat1069** [ale-sanchez-g/responsivefight#81]
Steps:
1. Start the battlefield challenge.
2.  'You are in battlefield` pop up appears.
3. In the background one can see the timer running. 
4. Allow the timer to run out completely and click `start`
5.  The player is now faced with the `try again` popup and hence is unable to take the challenge.

Expected:
1. Challenge timer does not begin unless player clicks start.

**Comment by ale-sanchez-g** [comment]
accepted bug

**Comment by ale-sanchez-g** [comment]
removed functionality in version 65
