### ISSUE TITLE
[UI] Clicking try again in battlefield challenge resets the entire game and player needs to start over

### ISSUE THREAD

**Issue by asbhat1069** [ale-sanchez-g/responsivefight#82]
Steps:
1. Create a played and start journey
2. Take the battlefields challenge.
3. Provide a wrong answer. Try again pop up appears.
4. Click try again.
5.  This resets the game and player is redirected to player creation page

Expected:
1. Player can try to answer the question again on clicking try again.

**Comment by ale-sanchez-g** [comment]
changed text, user is expected to start again
