### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by SowmyalakshmiSN** [ale-sanchez-g/responsivefight#84]
Post
Issue
1.Blank i.e. Null  Username is accepted
2.Negative Score is accepted
3.Username accepts more than 10 characters ,but in Website it is mentioned as only 10 characters allowed

GET

Issue:
1.Cannot get Specific user details, in general all users details is fetch ,it is good to Have such feature for API

PUT
No issues Found specific to Put, but similar issues like POST were found

1.Blank i.e. Null  Username is accepted
2.Negative Score is accepted
3.Username accepts more than 10 characters ,but in Website it is mentioned as only 10 characters allowed

Delete
I was not able to execute as I did not find delete-key parameter. I am assuming its built for security reasons i.e. to make sure only authorised person have access to delete user

**Comment by ale-sanchez-g** [comment]
These issues are acceptable and will look at improving the API.

Have made the DB table to only take 10 char on the name moving forward and will need to add better error handling.

We need to look at improve PUT and create PATCH for smaller changes
