### ISSUE TITLE
Web Issues

### ISSUE THREAD

**Issue by SowmyalakshmiSN** [ale-sanchez-g/responsivefight#85]
1.Blank name is accepted in User creation page http://responsivefight.herokuapp.com/ 
2.If user exists ,there is no coding done to accept a unique username. Instead new user score will add to old score.
3.We do not have option to select old user which is already created in previous game.

Check Score in Web

1.Each game has a points displayed at the popup, but the achieved score is not displayed for "Are you Game?" Battlefield, due to this there is some confusion in allocation of score.

**Comment by ale-sanchez-g** [comment]
This is as per design, will look at creating a sign-in process in the future, and how to present better the scores as the user progress through the game
