### ISSUE TITLE
Multiple issues.

### ISSUE THREAD

**Issue by rijvananas** [ale-sanchez-g/responsivefight#88]
1) when the screen is in responsive ( mobile) mode ( select the Iphone6/7/8) - Text is not fully visible.
<img width="959" alt="Responsive screen" src="https://user-images.githubusercontent.com/74528581/132214915-28ed1c0c-efa7-4ff9-87c8-0341352a2182.PNG"> Expected: when user sees the page in Mobile. Mobile should display full text completely.
2)when I was on this page - https://responsivefight.herokuapp.com/bus# and clicked the 'check your final score' button. 
Returned the scores of all users and navigates to the leaderboard page. Expected: should return only specific login -ed user score. 
3) Unable to navigate to home page directly. the only way to navigate is by clicking the back button in the browser.
4) when I clicked the button(start your journey) without typing the warier name, Api is returning 400 error code  and no proper error message.
{"error":"error: duplicate key value violates unique constraint \"leaderboard_username_key\"\n    at Connection.parseE (/app/node_modules/pg/lib/connection.js:581:48)\n    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:380:19)\n    at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:116:22)\n    at TLSSocket.emit (node:events:369:20)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:227:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)"}

**Comment by ale-sanchez-g** [comment]
Point 1 are multiple issues in 1, please split them if possible for better tracking and to look at prioratizing them
Point 2 is by design, but thanks for the feedback
Point 3 is handling empty, and to enable quick test in production. Will not fix

**Comment by ale-sanchez-g** [comment]
functionalities removed on version 65
