### ISSUE TITLE
Application is down

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#90]
<img width="1677" alt="Screen Shot 2021-09-11 at 8 23 21 pm" src="https://user-images.githubusercontent.com/62487509/132944735-0034d8bc-1694-4910-b4a0-45b73ea4aceb.png">

I tried to use the application but after a couple of questions it became unresponsive

**Comment by ale-sanchez-g** [comment]
This is a critical issue due to incorrect JSON formating

**Comment by ale-sanchez-g** [comment]
@chiragmadaan  defect should be resolved within the next 30 min, you can retry your testing after PR is merged
