### ISSUE TITLE
News questions aren't loaded is username has special characters

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#94]
Steps:
1. Go to https://responsivefight.herokuapp.com/
2. Enter username as !@#$%^&*()
3. Click on the "Create Warrior" button
4. Click on "Start your journey" button
5. Click on "Are you game?" button
6. On /news page, click on the start button to begin the quiz

Result: Question and options aren't loaded.
Expected: Question should load is the special characters are acceptable username, if special character usernames are not accepted then error should be shown on the home page.
<img width="1259" alt="Screen Shot 2021-09-12 at 12 58 41 pm" src="https://user-images.githubusercontent.com/62487509/132970033-693bc77f-50df-43b5-b299-75f263919dfe.png">

**Comment by ale-sanchez-g** [comment]
Bug accepted

**Comment by ale-sanchez-g** [comment]
invalid defect
