### ISSUE TITLE
[Minor UI bug] Not enough screen time for the last element of the ticker

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#96]
On the inner pages the ticker is shown. The last element of the ticker is "Visit WHO.int for more information.". The ticker resets to the first element as soon as the last element is completely visible, leaving it not enough screen time.

Expected: Ticker should reset when the last element reaches the left edge of the window, giving each ticker element equal screen time

**Comment by ale-sanchez-g** [comment]
unable to replicate
