### ISSUE TITLE
[QA Requirement] Missing ID for the "Return Home" button on /bus page

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#98]
There are 2 buttons in #bus_out_of_time_modal on /bus page, Try again and Return Home. Try again button has an ID i.e. retry. But the Return Home button doesn't have an ID. There is no unique constraint for the second button. There are few different ways to access it like xpath, get both buttons and then click second one, using css locator with a particular text but they are not recommended.

**Comment by ale-sanchez-g** [comment]
functionality removed on version 65
