### ISSUE TITLE
Bus timer doesn't pause on giving incorrect answer

### ISSUE THREAD

**Issue by chiragmadaan** [ale-sanchez-g/responsivefight#99]
Steps:
1. Start the "Take the bus" quiz
2. Click on the start button on /bus
3. Give incorrect answer for the first question
4. #bus_incorrect_modal will be shown, don't click anywhere and wait for a few seconds

Result: Timer continues in the background and when timer runs out, the #bus_out_of_time_modal is shown
Expected: Timer should pause and user's input should be awaited

**Comment by ale-sanchez-g** [comment]
remove on version 65
